# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Full test

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10","3.13"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: astral-sh/ruff-action@v2 # Fail fast if there are any linting errors
      with:
        version: 0.6.2
        src: "modelskill"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
    - name: Install fmdap
      run: |
        pip install .[test]
    - name: Test with pytest
      run: |
        pytest --cov=fmdap --ignore tests/notebooks/
